#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 12 12:01:32 2019

@author: bwhite2
"""

##CVAP- 13 districts

#####Plans for 13 Districts- CVAP
    ##Convert to geopackage 
num_districts = 13
output_dirname = "Run_1"

newdir = "./Outputs/"
os.makedirs(os.path.dirname(newdir + "init.txt"), exist_ok=True)
with open(newdir + "init.txt", "w") as f:
    f.write("Created Folder")
    
graph = Graph.from_json("/Users/bwhite2/GeorgiaCitizenship/ga_2012_BG.json")
df = gpd.read_file("/Users/bwhite2/GeorgiaCitizenship/ga_2012_bgs.gpkg")

# SUMMING DATA WE WANT IN THE DATAFRAME
#CVAP 

CVAP TOTAL: CVAP_EST TOT
BCVAP : CVAP_EST NH_BLACK
HCVAP:CVAP_EST HISP

new_cols = ['CVAP', 'BCVAP', 'HCVAP', 'minCVAP']


CVAP_cols = ['CVAP_EST TOT', ]
BCVAP_cols = ['CVAP_EST NH_BLACK', ]
HCVAP_cols = ['CVAP_EST HISP', ]


df['CVAP'] = pd.to_numeric(df['CVAP_EST TOT'])
df['BCVAP'] = pd.to_numeric(df['CVAP_EST NH_BLACK'])
df['HCVAP'] = pd.to_numeric(df['CVAP_EST HISP'])
df['minCVAP'] = df['BCVAP'] + df['HCVAP'] )

# ADD NEW DATA TO GRAPH 

graph.add_data(df, columns=new_cols)
# INITIAL PARTITION ASSIGNMENT USING RECURSIVE TREE PARTITION

starts = []

for i in range(1):
    starts.append(recursive_tree_part(graph,range(num_districts),df['CVAP'].sum()/num_districts, "CVAP", .001, 1))
# In[95]:


updater = {
    "population": updaters.Tally("CVAP", alias="population"),
    "cut_edges": cut_edges,
    "minCVAP":Election("minCVAP", {"minCVAP":"minCVAP"})}

   

initial_partitions = []
proposals = []
compactness_bounds = []
chains=[]

for i in range(1):
    initial_partitions.append(Partition(graph,starts[i], updater))
    print("initial partition is made")

    proposals.append(partial(
        recom, pop_col="CVAP", pop_target=df['CVAP'].sum()/num_districts, epsilon=0.01, node_repeats=1 # e = .02
    ))

    compactness_bounds.append(constraints.UpperBound(
        lambda p: len(p["cut_edges"]), 2 * len(initial_partitions[i]["cut_edges"])
    ))

    chains.append(MarkovChain(
        proposal=proposals[i],
        constraints=[
            constraints.within_percent_of_ideal_population(initial_partitions[i], .01), compactness_bounds[i] # e = .05
          #constraints.single_flip_contiguous#no_more_discontiguous 
        #constraints.within_percent_of_ideal_population(initial_partitions[i], .3)
        ],
        accept=always_accept,
        initial_state=initial_partitions[i],
        total_steps=10000
    ))
    
    
cuts=[[],[],[],[]]
minCPOP=[[],[],[],[]]

# Minority opportunity district in GA- Combined Black & Latino

for i in range(1):
    t = 0
    for part in chains[i]:
        cuts[i].append(len(part["cut_edges"]))
        minCPOP[i].append(sorted(part["minCVAP"].percents("minCVAP")))
        t+=1
    
        if t%100 ==0:
            print("chain",i,"step",t)
            
            df["current"]=df.index.map(dict(part.assignment))
        
            df.plot(column="current",cmap="jet")
            plt.close()

            with open(newdir+"assignment"+str(t)+".json", 'w') as jf1:
                json.dump(dict(part.assignment), jf1)
    
    print(f"finished chain {i}")

df["final"]=df.index.map(dict(part.assignment))

df.plot(column="final",cmap="jet")
plt.savefig(newdir+"final.png")
plt.close()



# In[94]:


# PLOT SORTED DISTRICTS OVER BVAP %

c='k'

#opportunity district minCVAP range in GA

plt.figure()
plt.boxplot(
            np.array(minCVAP[0]),
            whis=[1, 99],
            showfliers=False,
            patch_artist=True,
            boxprops=dict(facecolor="None", color=c),
            capprops=dict(color=c),
            whiskerprops=dict(color=c),
            flierprops=dict(color=c, markeredgecolor=c),
            medianprops=dict(color=c),
)

#plt.plot([1,2,3,4,5,6,7],[.233,.268,.268,.297,.322,.337,.621], 'o', color="hotpink", label="Enacted",markersize=10)

plt.axhline(y=.4,color='r',label="40%",linewidth=5)

plt.axhline(y=.45,color='y',label="45%",linewidth=5)

plt.axhline(y=.5,color='g',label="50%",linewidth=5)
plt.plot([],[],color='k',label="ReCom Ensemble")
plt.xlabel("Sorted Districts")
plt.ylabel("minCVAP%")

plt.legend()

plt.show()


# PLOT SORTED DISTRICTS OVER CVAP %

plt.figure()
plt.boxplot(
            np.array(CVAPS[0]),
            whis=[1, 99],
            showfliers=False,
            patch_artist=True,
            boxprops=dict(facecolor="None", color=c),
            capprops=dict(color=c),
            whiskerprops=dict(color=c),
            flierprops=dict(color=c, markeredgecolor=c),
            medianprops=dict(color=c),
)

#plt.plot([1,2,3,4,5,6,7],[.233,.268,.268,.297,.322,.337,.621], 'o', color="hotpink", label="Enacted",markersize=10)

plt.axhline(y=.4,color='r',label="40%",linewidth=5)

plt.axhline(y=.45,color='y',label="45%",linewidth=5)

plt.axhline(y=.5,color='g',label="50%",linewidth=5)
plt.plot([],[],color='k',label="ReCom Ensemble")
plt.xlabel("Sorted Districts")
plt.ylabel("CVAP%")

plt.legend()

plt.show()


# In[ ]:

